=head1 NAME

Sample::VendingMachine -

=head1 SYNOPSIS

  use Sample::VendingMachine;

=head1 DESCRIPTION

Sample::VendingMachine is

=head1 AUTHOR

kozaki tsuneaki E<lt>kozaki.tsuneaki@gmail.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

